---
- hosts: all
  tasks:
    - name: Install vim 
      apt:
        name: vim

    - name: Install whois tools
      apt:
        name: whois

    - name: Install tlp
      apt:
        name: tlp

    - name: Install tlp-rdw
      apt:
        name: tlp-rdw

    - name: Install tp-smapi-dkms
      apt:
        name: tp-smapi-dkms

    - name: Install acpi-call-dkms
      apt:
        name: acpi-call-dkms

    - name: Install openvpn
      apt:
        name: openvpn

    - name: Setup openvpn autostart
      lineinfile:
        path: /etc/default/openvpn
        line: 'AUTOSTART=all'

    - name: Install default JRE
      apt:
        name: default-jre

    - name: Install qemu-kvm
      apt:
        name: qemu-kvm

    - name: Install libvirt-bin
      apt:
        name: libvirt-bin

    - name: Install virtinst
      apt:
        name: virtinst

    - name: Install bridge-utils
      apt:
        name: bridge-utils

    - name: Install cpu-checker
      apt:
        name: cpu-checker

    - name: Install virt-manager
      apt:
        name: virt-manager

    - name: Install net-tools
      apt:
        name: net-tools

    - name: Install jq
      apt:
        name: jq
  
    - name: Install Docker
      apt:
        name: docker.io
  
    - name: Install awscli
      pip:
        name: awscli

    - name: Install kubectl v1.6.4
      command: chdir=/tmp {{ item }}
      with_items:
        - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.6.4/bin/linux/amd64/kubectl
        - chmod +x ./kubectl
        - mv -f -t /usr/local/bin /tmp/kubectl

    - name: Install kops 1.6.1
      command: chdir=/tmp {{ item }}
      with_items:
        - curl -LO https://github.com/kubernetes/kops/releases/download/1.6.1/kops-linux-amd64
        - chmod +x ./kops-linux-amd64
        - mv -f /tmp/kops-linux-amd64 /usr/local/bin/kops

    - name: Install minikube v0.19.0
      apt:
        deb: https://github.com/kubernetes/minikube/releases/download/v0.19.0/minikube_0.19-0.deb
    
    - name: Install VS Code v1.13
      apt:
        deb: https://az764295.vo.msecnd.net/stable/379d2efb5539b09112c793d3d9a413017d736f89/code_1.13.1-1497464373_amd64.deb

    - name: Install Terraform v0.9.8
      command: chdir=/tmp {{ item }}
      with_items:
        - curl -LO https://releases.hashicorp.com/terraform/0.9.8/terraform_0.9.8_linux_amd64.zip
        - unzip /tmp/terraform_0.9.8_linux_amd64.zip -d /tmp
        - chmod +x /tmp/terraform
        - mv -f -t /usr/local/bin /tmp/terraform
