---
- hosts: all
  tasks:
    - name: Install vim
      apt:
        name: vim

    - name: Install whois tools
      apt:
        name: whois

    - name: Install tlp
      apt:
        name: tlp

    - name: Install tlp-rdw
      apt:
        name: tlp-rdw

    - name: Install tp-smapi-dkms
      apt:
        name: tp-smapi-dkms

    - name: Install acpi-call-dkms
      apt:
        name: acpi-call-dkms

    - name: Install openvpn
      apt:
        name: openvpn

    - name: Setup openvpn autostart
      lineinfile:
        path: /etc/default/openvpn
        line: 'AUTOSTART=all'

    - name: Install default JRE
      apt:
        name: default-jre

    - name: Install qemu-kvm
      apt:
        name: qemu-kvm

    - name: Install libvirt-bin
      apt:
        name: libvirt-bin

    - name: Install virtinst
      apt:
        name: virtinst

    - name: Install bridge-utils
      apt:
        name: bridge-utils

    - name: Install cpu-checker
      apt:
        name: cpu-checker

    - name: Install virt-manager
      apt:
        name: virt-manager

    - name: Install net-tools
      apt:
        name: net-tools

    - name: Install jq
      apt:
        name: jq

    - name: Install Docker
      apt:
        name: docker.io

    - name: Install mysql client
      apt:
        name: mysql-client-core-5.7

    - name: Install postgresql client
      apt:
        name: postgresql-client

    - name: Install awscli
      pip:
        name: awscli

    - name: Install docker-py
      pip:
        name: docker-py

    - name: Install kubectl v1.7.6
      command: chdir=/tmp {{ item }}
      with_items:
        - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.7.6/bin/linux/amd64/kubectl
        - chmod +x ./kubectl
        - mv -f -t /usr/local/bin /tmp/kubectl

    - name: Install kops 1.7.0
      command: chdir=/tmp {{ item }}
      with_items:
        - curl -LO https://github.com/kubernetes/kops/releases/download/1.7.0/kops-linux-amd64
        - chmod +x ./kops-linux-amd64
        - mv -f /tmp/kops-linux-amd64 /usr/local/bin/kops

    - name: Install Helm 2.6.1
      command: chdir=/tmp {{ item }}
      with_items:
        - curl -LO https://storage.googleapis.com/kubernetes-helm/helm-v2.6.1-linux-amd64.tar.gz
        - tar zxvf helm-v2.6.1-linux-amd64.tar.gz
        - mv -f -t /usr/local/bin /tmp/linux-amd64/helm

    - name: Install minikube v0.22.2
      apt:
        deb: https://github.com/kubernetes/minikube/releases/download/v0.22.2/minikube_0.22-2.deb

    - name: Install VS Code v1.16
      apt:
        deb: https://az764295.vo.msecnd.net/stable/27492b6bf3acb0775d82d2f87b25a93490673c6d/code_1.16.1-1505406497_amd64.deb

    - name: Install Kapacitor CLI v1.3.1
      apt:
        deb: https://dl.influxdata.com/kapacitor/releases/kapacitor_1.3.1_amd64.deb

    - name: Install Terraform v0.10.6
      command: chdir=/tmp {{ item }}
      with_items:
        - curl -LO https://releases.hashicorp.com/terraform/0.10.6/terraform_0.10.6_linux_amd64.zip
        - unzip /tmp/terraform_0.10.6_linux_amd64.zip -d /tmp
        - chmod +x /tmp/terraform
        - mv -f -t /usr/local/bin /tmp/terraform
