---
- hosts: all
  tasks:
    - name: Install nvm
      shell: >
        curl https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
        creates=/home/{{ ansible_user_id }}/.nvm/nvm.sh